# Generated by Django 3.2.6 on 2021-08-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmdb_app', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reviews',
            constraint=models.CheckConstraint(check=models.Q(('stars__gte', 1), ('stars__lte', 10)), name='O campo stars aceita somente valores de 1 a 10.'),
        ),
    ]
